name = "Percy"
the_day = "Saturday"
the_date = "22"
the_year = "1993"
name = "new variable"
name = "Ginny"
the_day = "new variable"
the_day = "Sunday"
the_date = "new variable"
the_date = "18"
the_year = "new variable"
the_year = "1997"
puts "The family of #{name} proudly invite you to their graduation commencement on #{the_day} the #{the_date} of May #{the_year}. Festivities will be held at The Burrow. See you then!"
